sp:
  user-service:
    users: "[{\"id\":1, \"username\":\"abc\",\"password\":\"987\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"368\"}]"

spring:
  application:
    name: user-service
    cloud:
    config:
      override-none: true
server:
  port: 8102
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka  
